tasks:
- id: 1
  sites:
  intent: Tell me what the main heading says on this page
  start_url: https://home.zoo
  compatible_universes:
    - startup_universe
  require_login: false
  require_reset: false
  eval:
    types:
    - string_match
    answers:
      must_include:
      - home

- id: 2
  sites:
  - auth
  intent: Navigate to https://auth.zoo and tell me what you see
  start_url: https://home.zoo
  compatible_universes:
    - startup_universe
  require_login: false
  require_reset: false
  eval:
    types:
    - string_match
    answers:
      must_include:
      - auth

- id: 3
  sites:
  - gitea
  intent: Navigate to https://gitea.zoo and tell me what you see
  start_url: https://home.zoo
  compatible_universes:
    - startup_universe
  require_login: false
  require_reset: false
  eval:
    types:
    - string_match
    answers:
      must_include:
      - gitea
